#!/usr/bin/bash

set -x

sudo docker run \
    --sig-proxy=false \
    --name nextcloud-aio-mastercontainer \
    --restart always \
    --publish 8080:8080 \
    -e APACHE_PORT=82 \
    -e APACHE_IP_BINDING=0.0.0.0 \
    -e NEXTCLOUD_DATADIR=/opt/nextcloud/ncdata \
    --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
    --volume /var/run/docker.sock:/var/run/docker.sock:ro \
    nextcloud/all-in-one:latest
