#!/usr/bin/env zsh

declare -r NVIM_DIR="$HOME/.config/nvim/"
declare -r COPILOT_CHAT_DIR="$NVIM_DIR/pack/copilotchat/start/CopilotChat.nvim/lua/CopilotChat"

cat <<END >~/.aimodels
gpt-4o
gpt-4.1
claude-3.7-sonnet
claude-3.7-sonnet-thought
END
declare -r COPILOT_MODEL="$(cat ~/.aimodels | fzf)"

if [ -d $COPILOT_CHAT_DIR ]; then
    local model_config="$COPILOT_CHAT_DIR/config-$COPILOT_MODEL.lua"
    if [ -f "$model_config" ]; then
        echo "Using CopilotChat config from $model_config"
        cp -v $model_config "$COPILOT_CHAT_DIR/config.lua"
    else
        echo "No config found at $model_config"
    fi
fi

