apply:
	kubectl apply -f pv.yaml
	kubectl apply -f pvc.yaml
	kubectl apply -f deployment.yaml
	kubectl apply -f service.yaml

delete:
	kubectl delete -f service.yaml
	kubectl delete -f deployment.yaml
	kubectl delete -f pvc.yaml
	kubectl delete -f pv.yaml
