apply:
	kubectl apply -f namespace.yaml
	kubectl apply -f persistent-volume.yaml
	kubectl apply -f service.yaml
	kubectl apply -f deployment.yaml
	kubectl apply -f ingress.yaml

delete:
	kubectl delete -f ingress.yaml
	kubectl delete -f service.yaml
	kubectl delete -f deployment.yaml
	kubectl delete -f persistent-volume.yaml
