# If shell is interactive
if [[ ! -z "$PS1" && ! -f $HOME/.nozsh ]]; then
  # Use ZSH if it's installed
  if [ -e /opt/local/bin/zsh ]; then
    exec /opt/local/bin/zsh
  elif [ -e /bin/zsh ]; then
    exec /bin/zsh
  elif [ -e /usr/bin/zsh ]; then
    exec /usr/bin/zsh
  elif [ -e /data/data/com.termux/files/usr/bin/zsh ]; then
    exec /data/data/com.termux/files/usr/bin/zsh
  fi

  echo 'I might want to install zsh on this host'
fi
